export const SET_LOADING = 'SET_LOADING'
export const SET_QUIZ = 'SET_QUIZ'
export const SET_QUESTION='SET_QUESTION'
// export const REMOVE_STORY = 'REMOVE_STORY'
// export const HANDLE_PAGE = 'HANDLE_PAGE'
// export const HANDLE_SEARCH = 'HANDLE_SEARCH'